
package clientews.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "INoteDao", targetNamespace = "http://interfaces/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface INoteDao {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://interfaces/", className = "clientews.servicio.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.AddResponse")
    @Action(input = "http://interfaces/INoteDao/addRequest", output = "http://interfaces/INoteDao/addResponse")
    public boolean add(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://interfaces/", className = "clientews.servicio.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.UpdateResponse")
    @Action(input = "http://interfaces/INoteDao/updateRequest", output = "http://interfaces/INoteDao/updateResponse")
    public boolean update(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://interfaces/", className = "clientews.servicio.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.DeleteResponse")
    @Action(input = "http://interfaces/INoteDao/deleteRequest", output = "http://interfaces/INoteDao/deleteResponse")
    public boolean delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clientews.servicio.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAllResponse")
    @Action(input = "http://interfaces/INoteDao/getAllRequest", output = "http://interfaces/INoteDao/getAllResponse")
    public List<User> getAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clientews.servicio.Note>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllByUser", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAllByUser")
    @ResponseWrapper(localName = "getAllByUserResponse", targetNamespace = "http://interfaces/", className = "clientews.servicio.GetAllByUserResponse")
    @Action(input = "http://interfaces/INoteDao/getAllByUserRequest", output = "http://interfaces/INoteDao/getAllByUserResponse")
    public List<Note> getAllByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
